spring:
  profiles:
    default: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOST}:3306/stockoneq?serverTimezone=UTC
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 50

  config:
    import:
      - application-firebase.yml

  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 2592000
  refresh-token-validity: 2592000