spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOST}:3306/stockoneq?serverTimezone=UTC
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 50

  config:
    import:
      - classpath:secret.yml

  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error