spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL;
    username: root
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 50

  config:
    import:
      - classpath:secret.yml

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error